id: IB7F34DF5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T10:56:12+00:00'
last_modified: '2022-06-08T18:15:53.224841+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2CZ8069
  title: ལམ་རིམ་སྙིང་བསྡུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B171:
      image_group_id: I1PD96646
      title: Volume 1 of lam rim snying bsdus
      total_pages: 108
      order: 1
      base_file: B171.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
