id: P008077
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 12:59:54.888263
source_metadata:
  id: bdr:W2CZ8069
  title: ལམ་རིམ་སྙིང་བསྡུས།
  author: ''
  volumes:
    dbd5a129d0384753bfd3f44b4df6df5b:
      image_group_id: I1PD96646
      title: Volume 1 of lam rim snying bsdus
      volume_number: 1
      total_pages: 108
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
