id: P008077
initial_creation_type: ocr
source_metadata:
  id: bdr:W2CZ8069
  title: ལམ་རིམ་སྙིང་བསྡུས།
  author: ''
  volumes:
    14f77824b6404e809391388c56b3338d:
      image_group_id: I1PD96646
      title: ''
      volume_number: 1
      total_pages: 108
ebook_metadata:
  title: ལམ་རིམ་སྙིང་བསྡུས།
  author: ''
  sku: P008077
  cover: cover.jpg
  layers:
  - pagination
